type_dir: 'safebench/scenario/config/scenario_type_old_map'
type_name: 'dev.json'
route_dir: 'safebench/scenario/scenario_data/route'
method: 'advibm'
scenario_id: 5
route_id: null

ego_action_dim: 2
ego_state_dim: 4
ego_action_limit: 3.0
