method: 'standard' # benign, standard, dev
scenario_id: 5
data_path: 'safebench/scenario/scenario_data/data_shiqi'
route_path: /safebench/scenario/scenario_data/route_shiqi
ego_action_dim: 2
ego_state_dim: 4
