type_dir: 'safebench/scenario/config/scenario_type'
type_name: 'LC.json'
route_dir: 'safebench/scenario/scenario_data/route'
method: null
scenario_id: 2
route_id: null

ego_action_dim: 2
ego_state_dim: 4
ego_action_limit: 3.0

# for REINFORCE policy model
model_path: 'safebench/scenario/scenario_data/models/lc/1/0.pth'
standard_action: False
