type_dir: 'safebench/scenario/config/scenario_type_new_map'
type_name: 'standard.json'
route_dir: 'safebench/scenario/scenario_data/route_new_map'
method: null
scenario_id: null
route_id: null

ego_action_dim: 2
ego_state_dim: 4
