data: 'od.json' # benign, standard, dev, od
method: null
scenario_id: null
route_id: null
data_dir: 'safebench/scenario/scenario_data/data'
route_dir: 'safebench/scenario/scenario_data/route_od'
ego_action_dim: 2
ego_state_dim: 4
