type_dir: 'safebench/scenario/config/scenario_type'
type_name: 'standard.json'
route_dir: 'safebench/scenario/scenario_data/route'
method: null
scenario_id: 4
route_id: null

ego_action_dim: 2
ego_state_dim: 4
ego_action_limit: 3.0
